#page details
page:
  width: 21
  height: 29.7
  unit: cm
  margin:
    top: .5
    bottom: .3
    left: 1
    right: 1

#colors (typst accepts hex values as str)
colors:
  accent: ADD8E6
  main: "000"

#personal
name: John Doe
name_place: center
city: San Francisco
state: CA
email: xxx@example.com
github: https://github.com/typst
# portfolio: example.com


