#page details
page:
  width: 21
  height: 29.7
  unit: cm
  margin:
    top: .5
    bottom: .3
    left: 1
    right: 1


#personal
name: This Works
name_place: center
city: San Francisco
state: CA
email: xxx@example.com
github: https://github.com/typst
# portfolio: example.com


